---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# pivoteasy

<!-- badges: start -->
<!-- badges: end -->

The goal of pivoteasy is to make pivot table easily by specifying rows, columns, values and split.


## Installation

You can install the development version of pivoteasy from [GitHub](https://github.com/) with:

```{r, eval = FALSE}
# install.packages("devtools")
devtools::install_github("matutosi/pivoteasy")
```


You can also install from CRAN:

```{r, eval = FALSE}
install.packages("pivoteasy")
```

## Example

You can use pivot to make a pivot table easily.

```{r example}
library(pivoteasy)
library(dplyr)
library(ggplot2)
starwars %>%
  pivot(row = "homeworld", col = "species", value = "name", split = "sex")
msleep %>%
  pivot(row = "vore", col = "conservation", value = "name") %>%
  na2empty() %>%
  print(n = nrow(.))
as_tibble(Titanic) %>%
  pivot(row = "Age", col = c("Sex", "Survived"), value = "n", split = "Class")
diamonds %>%
  pivot(row = "cut", col = "color", value = "price", split = "clarity")
```
## Citation

Toshikazu Matsumura (2023) Create Pivot Table Easily. https://github.com/matutosi/pivoteasy/.
